version: "3.8"
services:
   website:
     build: ./website
     ports :
     - "3000:3000"
     volumes: 
     - "./website/src:/website/src"
     depends_on:
       - database
       - redis
   database:
      build: ./database
      environment: 
       - MYSQL_ROOT_PASSWORD=abc123
       - MYSQL_DATABASE=KdramaUnited
   redis:
    image: redis
   nginx:
      build: ./frontend-spa
      ports:
        - "8080:80"