version: "3"
services:
   website:
     build: ./website
     ports :
     - "3000:8080"
     volumes: 
     - "./website/src:/website/src"
     depends_on:
       - database
   database:
      build: ./database
      ports:
        - "3306:3306"
      environment: 
       - MYSQL_ROOT_PASSWORD=abc123
       - MYSQL_DATABASE=KdramaUnited