CREATE TABLE IF NOT EXISTS accounts (
	accountID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(50) NOT NULL,
	password VARCHAR(70) NOT NULL,
	CONSTRAINT usernameUnique UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS dramas(
    dramaID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    dramaName VARCHAR(50),
    dramaDescription VARCHAR(150),
    accountID INT UNSIGNED NOT NULL,
    FOREIGN KEY (accountID) REFERENCES accounts(accountID) ON DELETE CASCADE
   );

CREATE TABLE IF NOT EXISTS dramaRecensions(
    dramaRecensionID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    dramaRecensionDescription VARCHAR(150),
    dramaID INT UNSIGNED NOT NULL,
    accountID INT UNSIGNED NOT NULL,
    FOREIGN KEY (dramaID) REFERENCES dramas(dramaID) ON DELETE CASCADE,
    FOREIGN KEY (accountID) REFERENCES accounts(accountID) ON DELETE CASCADE
   );